#
# TransFig makefile
#

all: golomb_4_mirror.epic golomb_4_non_optimal.epic golomb_4_optimal.epic GR_first_sum.epic GR_order1.epic GR_order2.epic GR_quaternary_generation1.epic GR_quaternary_generation2.epic 

# translation into epic

golomb_4_mirror.tex: golomb_4_mirror.fig Makefile
	fig2dev -L epic golomb_4_mirror.fig golomb_4_mirror.tex
clean::
	rm -f golomb_4_mirror.epic


# translation into epic

golomb_4_non_optimal.tex: golomb_4_non_optimal.fig Makefile
	fig2dev -L epic golomb_4_non_optimal.fig golomb_4_non_optimal.tex
clean::
	rm -f golomb_4_non_optimal.epic


# translation into epic

golomb_4_optimal.tex: golomb_4_optimal.fig Makefile
	fig2dev -L epic golomb_4_optimal.fig golomb_4_optimal.tex
clean::
	rm -f golomb_4_optimal.epic


# translation into epic

GR_first_sum.tex: GR_first_sum.fig Makefile
	fig2dev -L epic GR_first_sum.fig GR_first_sum.tex
clean::
	rm -f GR_first_sum.epic


# translation into epic

GR_order1.tex: GR_order1.fig Makefile
	fig2dev -L epic GR_order1.fig GR_order1.tex
clean::
	rm -f GR_order1.epic


# translation into epic

GR_order2.tex: GR_order2.fig Makefile
	fig2dev -L epic GR_order2.fig GR_order2.tex
clean::
	rm -f GR_order2.epic


# translation into epic

GR_quaternary_generation1.tex: GR_quaternary_generation1.fig Makefile
	fig2dev -L epic GR_quaternary_generation1.fig GR_quaternary_generation1.tex
clean::
	rm -f GR_quaternary_generation1.epic


# translation into epic

GR_quaternary_generation2.tex: GR_quaternary_generation2.fig Makefile
	fig2dev -L epic GR_quaternary_generation2.fig GR_quaternary_generation2.tex
clean::
	rm -f GR_quaternary_generation2.epic

